#!/usr/bin/env bash

set -o nounset

out=`ping -c1 -W2 $GSR_ETCD_ENDPOINTS`

if [[ $? -eq 0 ]]; then
    return 0
else
    echo "" >> $ERRLOG
    echo "======================== <ping_endpoints> =========" >> $ERRLOG
    echo "" >> $ERRLOG
    echo "$out" >> $ERRLOG
    echo "" >> $ERRLOG
    echo "======================== </ping_endpoints> ========" >> $ERRLOG
    echo "" >> $ERRLOG
    return 1
fi
