// Code generated by protoc-gen-go.
// source: organization.proto
// DO NOT EDIT!

package procession

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// The top-most grouping of users of the system. A user may have permissions to
// read or take action within one or more Organizations.
type Organization struct {
	Uuid        string       `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	DisplayName string       `protobuf:"bytes,2,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
	Slug        string       `protobuf:"bytes,3,opt,name=slug" json:"slug,omitempty"`
	ParentUuid  *StringValue `protobuf:"bytes,4,opt,name=parent_uuid,json=parentUuid" json:"parent_uuid,omitempty"`
	Generation  uint32       `protobuf:"varint,100,opt,name=generation" json:"generation,omitempty"`
}

func (m *Organization) Reset()                    { *m = Organization{} }
func (m *Organization) String() string            { return proto.CompactTextString(m) }
func (*Organization) ProtoMessage()               {}
func (*Organization) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Organization) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Organization) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Organization) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Organization) GetParentUuid() *StringValue {
	if m != nil {
		return m.ParentUuid
	}
	return nil
}

func (m *Organization) GetGeneration() uint32 {
	if m != nil {
		return m.Generation
	}
	return 0
}

type OrganizationGetRequest struct {
	Session *Session `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Search  string   `protobuf:"bytes,2,opt,name=search" json:"search,omitempty"`
}

func (m *OrganizationGetRequest) Reset()                    { *m = OrganizationGetRequest{} }
func (m *OrganizationGetRequest) String() string            { return proto.CompactTextString(m) }
func (*OrganizationGetRequest) ProtoMessage()               {}
func (*OrganizationGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *OrganizationGetRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *OrganizationGetRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type OrganizationSetFields struct {
	DisplayName *StringValue `protobuf:"bytes,1,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
	ParentUuid  *StringValue `protobuf:"bytes,2,opt,name=parent_uuid,json=parentUuid" json:"parent_uuid,omitempty"`
}

func (m *OrganizationSetFields) Reset()                    { *m = OrganizationSetFields{} }
func (m *OrganizationSetFields) String() string            { return proto.CompactTextString(m) }
func (*OrganizationSetFields) ProtoMessage()               {}
func (*OrganizationSetFields) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *OrganizationSetFields) GetDisplayName() *StringValue {
	if m != nil {
		return m.DisplayName
	}
	return nil
}

func (m *OrganizationSetFields) GetParentUuid() *StringValue {
	if m != nil {
		return m.ParentUuid
	}
	return nil
}

type OrganizationSetRequest struct {
	Session *Session               `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Search  *StringValue           `protobuf:"bytes,2,opt,name=search" json:"search,omitempty"`
	Changed *OrganizationSetFields `protobuf:"bytes,3,opt,name=changed" json:"changed,omitempty"`
}

func (m *OrganizationSetRequest) Reset()                    { *m = OrganizationSetRequest{} }
func (m *OrganizationSetRequest) String() string            { return proto.CompactTextString(m) }
func (*OrganizationSetRequest) ProtoMessage()               {}
func (*OrganizationSetRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *OrganizationSetRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *OrganizationSetRequest) GetSearch() *StringValue {
	if m != nil {
		return m.Search
	}
	return nil
}

func (m *OrganizationSetRequest) GetChanged() *OrganizationSetFields {
	if m != nil {
		return m.Changed
	}
	return nil
}

type OrganizationSetResponse struct {
	Organization *Organization `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
}

func (m *OrganizationSetResponse) Reset()                    { *m = OrganizationSetResponse{} }
func (m *OrganizationSetResponse) String() string            { return proto.CompactTextString(m) }
func (*OrganizationSetResponse) ProtoMessage()               {}
func (*OrganizationSetResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *OrganizationSetResponse) GetOrganization() *Organization {
	if m != nil {
		return m.Organization
	}
	return nil
}

type OrganizationListFilters struct {
	Uuids        []string `protobuf:"bytes,1,rep,name=uuids" json:"uuids,omitempty"`
	DisplayNames []string `protobuf:"bytes,2,rep,name=display_names,json=displayNames" json:"display_names,omitempty"`
	Slugs        []string `protobuf:"bytes,3,rep,name=slugs" json:"slugs,omitempty"`
}

func (m *OrganizationListFilters) Reset()                    { *m = OrganizationListFilters{} }
func (m *OrganizationListFilters) String() string            { return proto.CompactTextString(m) }
func (*OrganizationListFilters) ProtoMessage()               {}
func (*OrganizationListFilters) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *OrganizationListFilters) GetUuids() []string {
	if m != nil {
		return m.Uuids
	}
	return nil
}

func (m *OrganizationListFilters) GetDisplayNames() []string {
	if m != nil {
		return m.DisplayNames
	}
	return nil
}

func (m *OrganizationListFilters) GetSlugs() []string {
	if m != nil {
		return m.Slugs
	}
	return nil
}

type OrganizationListRequest struct {
	Session *Session                 `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Filters *OrganizationListFilters `protobuf:"bytes,2,opt,name=filters" json:"filters,omitempty"`
	Options *SearchOptions           `protobuf:"bytes,3,opt,name=options" json:"options,omitempty"`
}

func (m *OrganizationListRequest) Reset()                    { *m = OrganizationListRequest{} }
func (m *OrganizationListRequest) String() string            { return proto.CompactTextString(m) }
func (*OrganizationListRequest) ProtoMessage()               {}
func (*OrganizationListRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *OrganizationListRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *OrganizationListRequest) GetFilters() *OrganizationListFilters {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *OrganizationListRequest) GetOptions() *SearchOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type OrganizationMembersSetRequest struct {
	Session      *Session `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Organization string   `protobuf:"bytes,2,opt,name=organization" json:"organization,omitempty"`
	Add          []string `protobuf:"bytes,3,rep,name=add" json:"add,omitempty"`
	Remove       []string `protobuf:"bytes,4,rep,name=remove" json:"remove,omitempty"`
}

func (m *OrganizationMembersSetRequest) Reset()                    { *m = OrganizationMembersSetRequest{} }
func (m *OrganizationMembersSetRequest) String() string            { return proto.CompactTextString(m) }
func (*OrganizationMembersSetRequest) ProtoMessage()               {}
func (*OrganizationMembersSetRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *OrganizationMembersSetRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *OrganizationMembersSetRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *OrganizationMembersSetRequest) GetAdd() []string {
	if m != nil {
		return m.Add
	}
	return nil
}

func (m *OrganizationMembersSetRequest) GetRemove() []string {
	if m != nil {
		return m.Remove
	}
	return nil
}

type OrganizationMembersSetResponse struct {
	NumAdded   uint64 `protobuf:"varint,1,opt,name=num_added,json=numAdded" json:"num_added,omitempty"`
	NumRemoved uint64 `protobuf:"varint,2,opt,name=num_removed,json=numRemoved" json:"num_removed,omitempty"`
}

func (m *OrganizationMembersSetResponse) Reset()                    { *m = OrganizationMembersSetResponse{} }
func (m *OrganizationMembersSetResponse) String() string            { return proto.CompactTextString(m) }
func (*OrganizationMembersSetResponse) ProtoMessage()               {}
func (*OrganizationMembersSetResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *OrganizationMembersSetResponse) GetNumAdded() uint64 {
	if m != nil {
		return m.NumAdded
	}
	return 0
}

func (m *OrganizationMembersSetResponse) GetNumRemoved() uint64 {
	if m != nil {
		return m.NumRemoved
	}
	return 0
}

type OrganizationMembersListRequest struct {
	Session      *Session `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Organization string   `protobuf:"bytes,2,opt,name=organization" json:"organization,omitempty"`
}

func (m *OrganizationMembersListRequest) Reset()                    { *m = OrganizationMembersListRequest{} }
func (m *OrganizationMembersListRequest) String() string            { return proto.CompactTextString(m) }
func (*OrganizationMembersListRequest) ProtoMessage()               {}
func (*OrganizationMembersListRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *OrganizationMembersListRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *OrganizationMembersListRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func init() {
	proto.RegisterType((*Organization)(nil), "procession.Organization")
	proto.RegisterType((*OrganizationGetRequest)(nil), "procession.OrganizationGetRequest")
	proto.RegisterType((*OrganizationSetFields)(nil), "procession.OrganizationSetFields")
	proto.RegisterType((*OrganizationSetRequest)(nil), "procession.OrganizationSetRequest")
	proto.RegisterType((*OrganizationSetResponse)(nil), "procession.OrganizationSetResponse")
	proto.RegisterType((*OrganizationListFilters)(nil), "procession.OrganizationListFilters")
	proto.RegisterType((*OrganizationListRequest)(nil), "procession.OrganizationListRequest")
	proto.RegisterType((*OrganizationMembersSetRequest)(nil), "procession.OrganizationMembersSetRequest")
	proto.RegisterType((*OrganizationMembersSetResponse)(nil), "procession.OrganizationMembersSetResponse")
	proto.RegisterType((*OrganizationMembersListRequest)(nil), "procession.OrganizationMembersListRequest")
}

func init() { proto.RegisterFile("organization.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 534 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0xd5, 0x34, 0xa1, 0x21, 0xd7, 0x09, 0x42, 0x03, 0xb4, 0xa6, 0x88, 0x92, 0x4e, 0x37, 0xd9,
	0x10, 0xa4, 0x74, 0x83, 0x78, 0x2c, 0xd8, 0x94, 0x0d, 0x50, 0x69, 0x22, 0x60, 0x47, 0x34, 0x8d,
	0x2f, 0xae, 0x91, 0x3d, 0x36, 0x33, 0x36, 0x08, 0xfe, 0x81, 0x3f, 0xe0, 0x2f, 0x10, 0x3b, 0x3e,
	0x0e, 0xcd, 0x23, 0x62, 0x9c, 0x36, 0x55, 0x15, 0x56, 0x9e, 0xfb, 0xbe, 0xe7, 0x9c, 0x19, 0x03,
	0x2d, 0x55, 0x2a, 0x64, 0xf6, 0x5d, 0xd4, 0x59, 0x29, 0x27, 0x95, 0x2a, 0xeb, 0x92, 0x42, 0xa5,
	0xca, 0x05, 0x6a, 0x9d, 0x95, 0x72, 0x6f, 0xa0, 0x51, 0xa8, 0xc5, 0x99, 0x8b, 0xec, 0x0d, 0xb5,
	0x73, 0x7b, 0xf3, 0xc6, 0x57, 0x25, 0xaa, 0x0a, 0x95, 0x76, 0x36, 0xfb, 0x45, 0x60, 0x70, 0x12,
	0xf4, 0xa3, 0x14, 0xba, 0x4d, 0x93, 0x25, 0x31, 0x19, 0x91, 0x71, 0x9f, 0xdb, 0x33, 0x3d, 0x80,
	0x41, 0x92, 0xe9, 0x2a, 0x17, 0xdf, 0xe6, 0x52, 0x14, 0x18, 0x6f, 0xd9, 0x58, 0xe4, 0x7d, 0x6f,
	0x44, 0x81, 0xa6, 0x4c, 0xe7, 0x4d, 0x1a, 0x77, 0x5c, 0x99, 0x39, 0xd3, 0xc7, 0x10, 0x55, 0x42,
	0xa1, 0xac, 0xe7, 0xb6, 0x63, 0x77, 0x44, 0xc6, 0xd1, 0x74, 0x77, 0xf2, 0x6f, 0xd5, 0xc9, 0xac,
	0x56, 0x99, 0x4c, 0xdf, 0x89, 0xbc, 0x41, 0x0e, 0x2e, 0xf7, 0xad, 0x19, 0xb8, 0x0f, 0x90, 0xa2,
	0x44, 0x65, 0x57, 0x8a, 0x93, 0x11, 0x19, 0x0f, 0x79, 0xe0, 0x61, 0x73, 0xd8, 0x09, 0x97, 0x7e,
	0x89, 0x35, 0xc7, 0xcf, 0x0d, 0xea, 0x9a, 0x3e, 0x84, 0x9e, 0x07, 0x6c, 0x11, 0x44, 0xd3, 0x5b,
	0xad, 0x79, 0xee, 0xcb, 0x97, 0x39, 0x74, 0x07, 0xb6, 0x1d, 0x5b, 0x1e, 0x93, 0xb7, 0xd8, 0x0f,
	0x02, 0x77, 0xc2, 0x09, 0x33, 0xac, 0x8f, 0x33, 0xcc, 0x13, 0x4d, 0x9f, 0xac, 0x70, 0x41, 0x2e,
	0x47, 0xd5, 0x22, 0x69, 0x85, 0x90, 0xad, 0x2b, 0x13, 0xc2, 0x7e, 0x93, 0x36, 0xe2, 0xd9, 0xc6,
	0x88, 0x1f, 0xb5, 0x10, 0x5f, 0x32, 0xde, 0xa7, 0xd1, 0xa7, 0xd0, 0x5b, 0x9c, 0x09, 0x99, 0x62,
	0x62, 0xc5, 0x8d, 0xa6, 0x07, 0x61, 0xc5, 0x85, 0x24, 0xf1, 0x65, 0x05, 0x7b, 0x0f, 0xbb, 0xe7,
	0xd6, 0xd6, 0x55, 0x29, 0x35, 0xd2, 0x67, 0x30, 0x08, 0x2f, 0xb2, 0x5f, 0x3e, 0x5e, 0xd7, 0x9c,
	0xb7, 0xb2, 0xd9, 0xa7, 0x76, 0xe3, 0x57, 0x99, 0xae, 0x8f, 0xb3, 0xbc, 0x46, 0xa5, 0xe9, 0x6d,
	0xb8, 0x66, 0xe8, 0xd5, 0x31, 0x19, 0x75, 0xc6, 0x7d, 0xee, 0x0c, 0x7a, 0x08, 0xc3, 0x50, 0x37,
	0x1d, 0x6f, 0xd9, 0xe8, 0x20, 0xd0, 0xc7, 0x96, 0x9a, 0x9b, 0xab, 0xe3, 0x8e, 0x2b, 0xb5, 0x06,
	0xfb, 0x43, 0xce, 0x0f, 0xdb, 0x90, 0xfd, 0xe7, 0xd0, 0xfb, 0xe8, 0xd6, 0xf4, 0xf4, 0x1f, 0xae,
	0xc3, 0x1b, 0x20, 0xe2, 0xcb, 0x1a, 0x7a, 0x04, 0xbd, 0xb2, 0x32, 0x51, 0xed, 0xb5, 0xb8, 0xdb,
	0x9e, 0x66, 0x04, 0x3b, 0x71, 0x09, 0x7c, 0x99, 0xc9, 0x7e, 0x12, 0xb8, 0x1f, 0x76, 0x7e, 0x8d,
	0xc5, 0x29, 0x2a, 0xbd, 0xf9, 0x15, 0x62, 0x2b, 0xca, 0xb9, 0xa7, 0xd3, 0xf2, 0xd1, 0x9b, 0xd0,
	0x11, 0x49, 0xe2, 0x79, 0x34, 0x47, 0xf3, 0xd4, 0x14, 0x16, 0xe5, 0x17, 0x8c, 0xbb, 0xd6, 0xe9,
	0x2d, 0xf6, 0x01, 0xf6, 0xd7, 0x6d, 0xe7, 0x6f, 0xca, 0x3d, 0xe8, 0xcb, 0xa6, 0x98, 0x8b, 0x24,
	0x41, 0xf7, 0x5f, 0xea, 0xf2, 0xeb, 0xb2, 0x29, 0x5e, 0x18, 0x9b, 0x3e, 0x80, 0xc8, 0x04, 0x5d,
	0x33, 0xf7, 0xa6, 0xba, 0x1c, 0x64, 0x53, 0x70, 0xe7, 0x61, 0xfa, 0xc2, 0xfe, 0xff, 0xa1, 0xe1,
	0x15, 0xe0, 0x9f, 0x6e, 0xdb, 0xbf, 0xeb, 0xd1, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xce, 0xb1,
	0xb1, 0xbe, 0xac, 0x05, 0x00, 0x00,
}
