// Code generated by protoc-gen-go.
// source: organization.proto
// DO NOT EDIT!

package procession

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// The top-most grouping of users of the system. A user may have permissions to
// read or take action within one or more Organizations.
type Organization struct {
	Uuid                   string       `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	DisplayName            string       `protobuf:"bytes,2,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
	Slug                   string       `protobuf:"bytes,3,opt,name=slug" json:"slug,omitempty"`
	ParentOrganizationUuid *StringValue `protobuf:"bytes,4,opt,name=parent_organization_uuid,json=parentOrganizationUuid" json:"parent_organization_uuid,omitempty"`
	Generation             uint32       `protobuf:"varint,100,opt,name=generation" json:"generation,omitempty"`
}

func (m *Organization) Reset()                    { *m = Organization{} }
func (m *Organization) String() string            { return proto.CompactTextString(m) }
func (*Organization) ProtoMessage()               {}
func (*Organization) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Organization) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Organization) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Organization) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Organization) GetParentOrganizationUuid() *StringValue {
	if m != nil {
		return m.ParentOrganizationUuid
	}
	return nil
}

func (m *Organization) GetGeneration() uint32 {
	if m != nil {
		return m.Generation
	}
	return 0
}

type GetOrganizationRequest struct {
	Session *Session `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Search  string   `protobuf:"bytes,2,opt,name=search" json:"search,omitempty"`
}

func (m *GetOrganizationRequest) Reset()                    { *m = GetOrganizationRequest{} }
func (m *GetOrganizationRequest) String() string            { return proto.CompactTextString(m) }
func (*GetOrganizationRequest) ProtoMessage()               {}
func (*GetOrganizationRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *GetOrganizationRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *GetOrganizationRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type OrganizationSetFields struct {
	DisplayName            *StringValue `protobuf:"bytes,1,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
	ParentOrganizationUuid *StringValue `protobuf:"bytes,2,opt,name=parent_organization_uuid,json=parentOrganizationUuid" json:"parent_organization_uuid,omitempty"`
}

func (m *OrganizationSetFields) Reset()                    { *m = OrganizationSetFields{} }
func (m *OrganizationSetFields) String() string            { return proto.CompactTextString(m) }
func (*OrganizationSetFields) ProtoMessage()               {}
func (*OrganizationSetFields) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *OrganizationSetFields) GetDisplayName() *StringValue {
	if m != nil {
		return m.DisplayName
	}
	return nil
}

func (m *OrganizationSetFields) GetParentOrganizationUuid() *StringValue {
	if m != nil {
		return m.ParentOrganizationUuid
	}
	return nil
}

type OrganizationSetRequest struct {
	Session *Session               `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Search  *StringValue           `protobuf:"bytes,2,opt,name=search" json:"search,omitempty"`
	Changed *OrganizationSetFields `protobuf:"bytes,3,opt,name=changed" json:"changed,omitempty"`
}

func (m *OrganizationSetRequest) Reset()                    { *m = OrganizationSetRequest{} }
func (m *OrganizationSetRequest) String() string            { return proto.CompactTextString(m) }
func (*OrganizationSetRequest) ProtoMessage()               {}
func (*OrganizationSetRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *OrganizationSetRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *OrganizationSetRequest) GetSearch() *StringValue {
	if m != nil {
		return m.Search
	}
	return nil
}

func (m *OrganizationSetRequest) GetChanged() *OrganizationSetFields {
	if m != nil {
		return m.Changed
	}
	return nil
}

type OrganizationSetResponse struct {
	Organization *Organization `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
}

func (m *OrganizationSetResponse) Reset()                    { *m = OrganizationSetResponse{} }
func (m *OrganizationSetResponse) String() string            { return proto.CompactTextString(m) }
func (*OrganizationSetResponse) ProtoMessage()               {}
func (*OrganizationSetResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *OrganizationSetResponse) GetOrganization() *Organization {
	if m != nil {
		return m.Organization
	}
	return nil
}

type OrganizationListFilters struct {
	Uuids        []string `protobuf:"bytes,1,rep,name=uuids" json:"uuids,omitempty"`
	DisplayNames []string `protobuf:"bytes,2,rep,name=display_names,json=displayNames" json:"display_names,omitempty"`
	Slugs        []string `protobuf:"bytes,3,rep,name=slugs" json:"slugs,omitempty"`
}

func (m *OrganizationListFilters) Reset()                    { *m = OrganizationListFilters{} }
func (m *OrganizationListFilters) String() string            { return proto.CompactTextString(m) }
func (*OrganizationListFilters) ProtoMessage()               {}
func (*OrganizationListFilters) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *OrganizationListFilters) GetUuids() []string {
	if m != nil {
		return m.Uuids
	}
	return nil
}

func (m *OrganizationListFilters) GetDisplayNames() []string {
	if m != nil {
		return m.DisplayNames
	}
	return nil
}

func (m *OrganizationListFilters) GetSlugs() []string {
	if m != nil {
		return m.Slugs
	}
	return nil
}

type OrganizationListRequest struct {
	Session *Session                 `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Filters *OrganizationListFilters `protobuf:"bytes,2,opt,name=filters" json:"filters,omitempty"`
	Options *SearchOptions           `protobuf:"bytes,3,opt,name=options" json:"options,omitempty"`
}

func (m *OrganizationListRequest) Reset()                    { *m = OrganizationListRequest{} }
func (m *OrganizationListRequest) String() string            { return proto.CompactTextString(m) }
func (*OrganizationListRequest) ProtoMessage()               {}
func (*OrganizationListRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *OrganizationListRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *OrganizationListRequest) GetFilters() *OrganizationListFilters {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *OrganizationListRequest) GetOptions() *SearchOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func init() {
	proto.RegisterType((*Organization)(nil), "procession.Organization")
	proto.RegisterType((*GetOrganizationRequest)(nil), "procession.GetOrganizationRequest")
	proto.RegisterType((*OrganizationSetFields)(nil), "procession.OrganizationSetFields")
	proto.RegisterType((*OrganizationSetRequest)(nil), "procession.OrganizationSetRequest")
	proto.RegisterType((*OrganizationSetResponse)(nil), "procession.OrganizationSetResponse")
	proto.RegisterType((*OrganizationListFilters)(nil), "procession.OrganizationListFilters")
	proto.RegisterType((*OrganizationListRequest)(nil), "procession.OrganizationListRequest")
}

func init() { proto.RegisterFile("organization.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcf, 0x6e, 0x13, 0x31,
	0x10, 0xc6, 0xe5, 0xa4, 0x34, 0xea, 0x64, 0xc3, 0xc1, 0x40, 0x6a, 0x7a, 0x40, 0xe9, 0xf6, 0x92,
	0x0b, 0x41, 0x4a, 0x6f, 0xfc, 0xb9, 0x96, 0x0b, 0xa2, 0xc2, 0x15, 0x70, 0x8c, 0x4c, 0x76, 0xd8,
	0x1a, 0x6d, 0xbd, 0x8b, 0xc7, 0x2b, 0x04, 0x0f, 0xc4, 0x1b, 0x70, 0xe3, 0x11, 0x78, 0x28, 0xb4,
	0xb6, 0x23, 0xbc, 0x2d, 0xc9, 0x21, 0xa7, 0xec, 0x78, 0xe6, 0x1b, 0x7f, 0xf3, 0x1b, 0x2b, 0xc0,
	0x6b, 0x5b, 0x2a, 0xa3, 0x7f, 0x28, 0xa7, 0x6b, 0xb3, 0x68, 0x6c, 0xed, 0x6a, 0x0e, 0x8d, 0xad,
	0xd7, 0x48, 0xa4, 0x6b, 0x73, 0x92, 0x11, 0x2a, 0xbb, 0xbe, 0x0e, 0x99, 0x93, 0x09, 0x85, 0xe3,
	0x18, 0xde, 0xff, 0x66, 0x55, 0xd3, 0xa0, 0xa5, 0x10, 0xe7, 0x7f, 0x18, 0x64, 0x97, 0x49, 0x3f,
	0xce, 0xe1, 0xa0, 0x6d, 0x75, 0x21, 0xd8, 0x8c, 0xcd, 0x8f, 0xa4, 0xff, 0xe6, 0xa7, 0x90, 0x15,
	0x9a, 0x9a, 0x4a, 0x7d, 0x5f, 0x19, 0x75, 0x83, 0x62, 0xe0, 0x73, 0xe3, 0x78, 0xf6, 0x56, 0xdd,
	0x60, 0x27, 0xa3, 0xaa, 0x2d, 0xc5, 0x30, 0xc8, 0xba, 0x6f, 0xfe, 0x0e, 0x44, 0xa3, 0x2c, 0x1a,
	0xb7, 0x4a, 0x1d, 0xaf, 0x7c, 0xfb, 0x83, 0x19, 0x9b, 0x8f, 0x97, 0xc7, 0x8b, 0x7f, 0xbe, 0x17,
	0x57, 0xce, 0x6a, 0x53, 0x7e, 0x50, 0x55, 0x8b, 0x72, 0x1a, 0x84, 0xa9, 0xb3, 0xf7, 0x9d, 0x93,
	0x27, 0x00, 0x25, 0x1a, 0xb4, 0xfe, 0x44, 0x14, 0x33, 0x36, 0x9f, 0xc8, 0xe4, 0x24, 0x5f, 0xc1,
	0xf4, 0x35, 0xf6, 0x64, 0x12, 0xbf, 0xb6, 0x48, 0x8e, 0x3f, 0x85, 0x51, 0x24, 0xe1, 0x47, 0x1b,
	0x2f, 0x1f, 0xf4, 0xee, 0x0e, 0xbf, 0x72, 0x53, 0xc3, 0xa7, 0x70, 0x18, 0x30, 0xc6, 0x61, 0x63,
	0x94, 0xff, 0x64, 0xf0, 0x28, 0x6d, 0x7f, 0x85, 0xee, 0x42, 0x63, 0x55, 0x10, 0x7f, 0x7e, 0x0b,
	0x12, 0xdb, 0x3d, 0x61, 0x8f, 0xde, 0x2e, 0x52, 0x83, 0xbd, 0x48, 0xe5, 0xbf, 0x18, 0x4c, 0x6f,
	0x19, 0xdd, 0x13, 0xc5, 0xb3, 0x1e, 0x8a, 0x1d, 0x56, 0x62, 0x19, 0x7f, 0x01, 0xa3, 0xf5, 0xb5,
	0x32, 0x25, 0x16, 0xfe, 0x39, 0x8c, 0x97, 0xa7, 0xa9, 0xe2, 0xbf, 0xf4, 0xe4, 0x46, 0x91, 0x7f,
	0x84, 0xe3, 0x3b, 0xb6, 0xa9, 0xa9, 0x0d, 0x21, 0x7f, 0x09, 0x59, 0x8a, 0x27, 0x9a, 0x17, 0xdb,
	0x9a, 0xcb, 0x5e, 0x75, 0xfe, 0xa5, 0xdf, 0xf8, 0x8d, 0x26, 0x77, 0xa1, 0x2b, 0x87, 0x96, 0xf8,
	0x43, 0xb8, 0xd7, 0xa1, 0x26, 0xc1, 0x66, 0xc3, 0xf9, 0x91, 0x0c, 0x01, 0x3f, 0x83, 0x49, 0xba,
	0x50, 0x12, 0x03, 0x9f, 0xcd, 0x92, 0xc5, 0x79, 0x69, 0xf7, 0xd6, 0x49, 0x0c, 0x83, 0xd4, 0x07,
	0xf9, 0x6f, 0x76, 0xf7, 0xb2, 0x3d, 0xe9, 0xbf, 0x82, 0xd1, 0xe7, 0x60, 0x33, 0xe2, 0x3f, 0xdb,
	0x36, 0x6f, 0x32, 0x91, 0xdc, 0x68, 0xf8, 0x39, 0x8c, 0xea, 0xa6, 0xcb, 0x52, 0xdc, 0xc5, 0xe3,
	0xfe, 0x6d, 0xdd, 0xc2, 0x2e, 0x43, 0x81, 0xdc, 0x54, 0x7e, 0x3a, 0xf4, 0xff, 0x0d, 0xe7, 0x7f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x74, 0x0f, 0xf0, 0x26, 0x6a, 0x04, 0x00, 0x00,
}
