// Code generated by protoc-gen-go.
// source: organization.proto
// DO NOT EDIT!

package procession

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// The top-most grouping of users of the system. A user may have permissions to
// read or take action within one or more Organizations.
type Organization struct {
	Uuid        string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
	Slug        string `protobuf:"bytes,3,opt,name=slug" json:"slug,omitempty"`
	Generation  uint32 `protobuf:"varint,100,opt,name=generation" json:"generation,omitempty"`
}

func (m *Organization) Reset()                    { *m = Organization{} }
func (m *Organization) String() string            { return proto.CompactTextString(m) }
func (*Organization) ProtoMessage()               {}
func (*Organization) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Organization) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Organization) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Organization) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Organization) GetGeneration() uint32 {
	if m != nil {
		return m.Generation
	}
	return 0
}

type GetOrganizationRequest struct {
	Session *Session `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Search  string   `protobuf:"bytes,2,opt,name=search" json:"search,omitempty"`
}

func (m *GetOrganizationRequest) Reset()                    { *m = GetOrganizationRequest{} }
func (m *GetOrganizationRequest) String() string            { return proto.CompactTextString(m) }
func (*GetOrganizationRequest) ProtoMessage()               {}
func (*GetOrganizationRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *GetOrganizationRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *GetOrganizationRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type SetOrganizationFields struct {
	DisplayName *StringValue `protobuf:"bytes,1,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
}

func (m *SetOrganizationFields) Reset()                    { *m = SetOrganizationFields{} }
func (m *SetOrganizationFields) String() string            { return proto.CompactTextString(m) }
func (*SetOrganizationFields) ProtoMessage()               {}
func (*SetOrganizationFields) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *SetOrganizationFields) GetDisplayName() *StringValue {
	if m != nil {
		return m.DisplayName
	}
	return nil
}

type SetOrganizationRequest struct {
	Session            *Session               `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Search             *StringValue           `protobuf:"bytes,2,opt,name=search" json:"search,omitempty"`
	OrganizationFields *SetOrganizationFields `protobuf:"bytes,3,opt,name=organization_fields,json=organizationFields" json:"organization_fields,omitempty"`
}

func (m *SetOrganizationRequest) Reset()                    { *m = SetOrganizationRequest{} }
func (m *SetOrganizationRequest) String() string            { return proto.CompactTextString(m) }
func (*SetOrganizationRequest) ProtoMessage()               {}
func (*SetOrganizationRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *SetOrganizationRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *SetOrganizationRequest) GetSearch() *StringValue {
	if m != nil {
		return m.Search
	}
	return nil
}

func (m *SetOrganizationRequest) GetOrganizationFields() *SetOrganizationFields {
	if m != nil {
		return m.OrganizationFields
	}
	return nil
}

type SetOrganizationResponse struct {
	Organization *Organization `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
}

func (m *SetOrganizationResponse) Reset()                    { *m = SetOrganizationResponse{} }
func (m *SetOrganizationResponse) String() string            { return proto.CompactTextString(m) }
func (*SetOrganizationResponse) ProtoMessage()               {}
func (*SetOrganizationResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *SetOrganizationResponse) GetOrganization() *Organization {
	if m != nil {
		return m.Organization
	}
	return nil
}

type ListOrganizationsFilters struct {
	Uuids        []string `protobuf:"bytes,1,rep,name=uuids" json:"uuids,omitempty"`
	DisplayNames []string `protobuf:"bytes,2,rep,name=display_names,json=displayNames" json:"display_names,omitempty"`
	Slugs        []string `protobuf:"bytes,3,rep,name=slugs" json:"slugs,omitempty"`
}

func (m *ListOrganizationsFilters) Reset()                    { *m = ListOrganizationsFilters{} }
func (m *ListOrganizationsFilters) String() string            { return proto.CompactTextString(m) }
func (*ListOrganizationsFilters) ProtoMessage()               {}
func (*ListOrganizationsFilters) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *ListOrganizationsFilters) GetUuids() []string {
	if m != nil {
		return m.Uuids
	}
	return nil
}

func (m *ListOrganizationsFilters) GetDisplayNames() []string {
	if m != nil {
		return m.DisplayNames
	}
	return nil
}

func (m *ListOrganizationsFilters) GetSlugs() []string {
	if m != nil {
		return m.Slugs
	}
	return nil
}

type ListOrganizationsRequest struct {
	Session *Session                  `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Filters *ListOrganizationsFilters `protobuf:"bytes,2,opt,name=filters" json:"filters,omitempty"`
	Options *SearchOptions            `protobuf:"bytes,3,opt,name=options" json:"options,omitempty"`
}

func (m *ListOrganizationsRequest) Reset()                    { *m = ListOrganizationsRequest{} }
func (m *ListOrganizationsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListOrganizationsRequest) ProtoMessage()               {}
func (*ListOrganizationsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *ListOrganizationsRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *ListOrganizationsRequest) GetFilters() *ListOrganizationsFilters {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *ListOrganizationsRequest) GetOptions() *SearchOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func init() {
	proto.RegisterType((*Organization)(nil), "procession.Organization")
	proto.RegisterType((*GetOrganizationRequest)(nil), "procession.GetOrganizationRequest")
	proto.RegisterType((*SetOrganizationFields)(nil), "procession.SetOrganizationFields")
	proto.RegisterType((*SetOrganizationRequest)(nil), "procession.SetOrganizationRequest")
	proto.RegisterType((*SetOrganizationResponse)(nil), "procession.SetOrganizationResponse")
	proto.RegisterType((*ListOrganizationsFilters)(nil), "procession.ListOrganizationsFilters")
	proto.RegisterType((*ListOrganizationsRequest)(nil), "procession.ListOrganizationsRequest")
}

func init() { proto.RegisterFile("organization.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x53, 0x4d, 0xaf, 0x12, 0x31,
	0x14, 0xcd, 0x80, 0x42, 0xb8, 0x0c, 0x2e, 0x8a, 0x42, 0x65, 0x61, 0x60, 0x74, 0xc1, 0x46, 0x4c,
	0x60, 0x67, 0x8c, 0x4b, 0xdc, 0x18, 0x49, 0x3a, 0x89, 0x2e, 0x49, 0x65, 0xca, 0xd8, 0x38, 0x4c,
	0xc7, 0xde, 0x99, 0x18, 0xfc, 0x71, 0xfe, 0x02, 0x7f, 0x94, 0x99, 0xb6, 0xc4, 0xd6, 0xc7, 0x7b,
	0x8b, 0x97, 0xb7, 0x9a, 0xde, 0x8f, 0xd3, 0x73, 0x4f, 0xcf, 0x1d, 0x20, 0x4a, 0xe7, 0xbc, 0x94,
	0xbf, 0x78, 0x2d, 0x55, 0xb9, 0xaa, 0xb4, 0xaa, 0x15, 0x81, 0x4a, 0xab, 0x83, 0x40, 0x94, 0xaa,
	0x9c, 0xc5, 0x28, 0xb8, 0x3e, 0x7c, 0xb3, 0x95, 0xd9, 0x08, 0x6d, 0xda, 0x85, 0x4f, 0x7e, 0x6a,
	0x5e, 0x55, 0x42, 0xa3, 0x8d, 0x93, 0x33, 0xc4, 0x3b, 0xef, 0x3a, 0x42, 0xe0, 0x51, 0xd3, 0xc8,
	0x8c, 0x46, 0xf3, 0x68, 0x39, 0x60, 0xe6, 0x4c, 0x16, 0x10, 0x67, 0x12, 0xab, 0x82, 0x9f, 0xf7,
	0x25, 0x3f, 0x09, 0xda, 0x31, 0xb5, 0xa1, 0xcb, 0x7d, 0xe2, 0x27, 0xd1, 0xc2, 0xb0, 0x68, 0x72,
	0xda, 0xb5, 0xb0, 0xf6, 0x4c, 0x5e, 0x00, 0xe4, 0xa2, 0x14, 0xda, 0x5c, 0x4c, 0xb3, 0x79, 0xb4,
	0x1c, 0x31, 0x2f, 0x93, 0xec, 0x61, 0xf2, 0x41, 0xd4, 0x3e, 0x3b, 0x13, 0x3f, 0x1a, 0x81, 0x35,
	0x79, 0x0d, 0x7d, 0x37, 0xb5, 0x99, 0x63, 0xb8, 0x1e, 0xaf, 0xfe, 0xe9, 0x5b, 0xa5, 0xf6, 0xcb,
	0x2e, 0x3d, 0x64, 0x02, 0x3d, 0x2b, 0xd9, 0x4d, 0xe6, 0xa2, 0x24, 0x85, 0x67, 0x69, 0x48, 0xb0,
	0x95, 0xa2, 0xc8, 0x90, 0xbc, 0xfd, 0x4f, 0x90, 0x25, 0x99, 0x06, 0x24, 0xb5, 0x96, 0x65, 0xfe,
	0x99, 0x17, 0x8d, 0x08, 0x94, 0x26, 0x7f, 0x22, 0x98, 0xa4, 0x0f, 0x32, 0xf6, 0x9b, 0x60, 0xec,
	0x3b, 0xf8, 0x5d, 0x1b, 0x61, 0x30, 0xf6, 0xad, 0xdf, 0x1f, 0x8d, 0x1a, 0xf3, 0xe6, 0xc3, 0xf5,
	0x22, 0xe4, 0xba, 0x22, 0x9b, 0x05, 0x8b, 0x63, 0x73, 0xc9, 0x17, 0x98, 0xde, 0x50, 0x83, 0x95,
	0x2a, 0x51, 0x90, 0x77, 0x10, 0xfb, 0x00, 0xa7, 0x89, 0xfa, 0x3c, 0x01, 0x2e, 0xe8, 0x4e, 0xbe,
	0x03, 0xfd, 0x28, 0x31, 0xb8, 0x19, 0xb7, 0xb2, 0xa8, 0x85, 0x46, 0xf2, 0x14, 0x1e, 0xb7, 0x8b,
	0x85, 0x34, 0x9a, 0x77, 0x97, 0x03, 0x66, 0x03, 0xf2, 0x12, 0x46, 0xbe, 0x2b, 0x48, 0x3b, 0xa6,
	0x1a, 0x7b, 0xaf, 0x6f, 0xa0, 0xed, 0x72, 0xb5, 0xaa, 0x0d, 0xd4, 0x04, 0xc9, 0xef, 0xe8, 0x0a,
	0xdb, 0x3d, 0x6d, 0x79, 0x0f, 0xfd, 0xa3, 0x9d, 0xd3, 0xf9, 0xf2, 0xca, 0x6f, 0xbf, 0x4d, 0x13,
	0xbb, 0x80, 0xc8, 0x06, 0xfa, 0xaa, 0x32, 0x25, 0xe7, 0xcc, 0xf3, 0x90, 0xae, 0xb5, 0x72, 0x67,
	0x1b, 0xd8, 0xa5, 0xf3, 0x6b, 0xcf, 0xfc, 0x8d, 0x9b, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe6,
	0xee, 0x2e, 0x20, 0xdc, 0x03, 0x00, 0x00,
}
