// Code generated by protoc-gen-go.
// source: service_iam.proto
// DO NOT EDIT!

package procession

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for IAM service

type IAMClient interface {
	// Returns information about a specific user
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	// Set information about a specific user
	SetUser(ctx context.Context, in *SetUserRequest, opts ...grpc.CallOption) (*SetUserResponse, error)
	// Returns information about multiple users
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (IAM_ListUsersClient, error)
}

type iAMClient struct {
	cc *grpc.ClientConn
}

func NewIAMClient(cc *grpc.ClientConn) IAMClient {
	return &iAMClient{cc}
}

func (c *iAMClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/procession.IAM/get_user", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) SetUser(ctx context.Context, in *SetUserRequest, opts ...grpc.CallOption) (*SetUserResponse, error) {
	out := new(SetUserResponse)
	err := grpc.Invoke(ctx, "/procession.IAM/set_user", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (IAM_ListUsersClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_IAM_serviceDesc.Streams[0], c.cc, "/procession.IAM/list_users", opts...)
	if err != nil {
		return nil, err
	}
	x := &iAMListUsersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type IAM_ListUsersClient interface {
	Recv() (*User, error)
	grpc.ClientStream
}

type iAMListUsersClient struct {
	grpc.ClientStream
}

func (x *iAMListUsersClient) Recv() (*User, error) {
	m := new(User)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for IAM service

type IAMServer interface {
	// Returns information about a specific user
	GetUser(context.Context, *GetUserRequest) (*User, error)
	// Set information about a specific user
	SetUser(context.Context, *SetUserRequest) (*SetUserResponse, error)
	// Returns information about multiple users
	ListUsers(*ListUsersRequest, IAM_ListUsersServer) error
}

func RegisterIAMServer(s *grpc.Server, srv IAMServer) {
	s.RegisterService(&_IAM_serviceDesc, srv)
}

func _IAM_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/procession.IAM/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_SetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).SetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/procession.IAM/SetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).SetUser(ctx, req.(*SetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_ListUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListUsersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IAMServer).ListUsers(m, &iAMListUsersServer{stream})
}

type IAM_ListUsersServer interface {
	Send(*User) error
	grpc.ServerStream
}

type iAMListUsersServer struct {
	grpc.ServerStream
}

func (x *iAMListUsersServer) Send(m *User) error {
	return x.ServerStream.SendMsg(m)
}

var _IAM_serviceDesc = grpc.ServiceDesc{
	ServiceName: "procession.IAM",
	HandlerType: (*IAMServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "get_user",
			Handler:    _IAM_GetUser_Handler,
		},
		{
			MethodName: "set_user",
			Handler:    _IAM_SetUser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "list_users",
			Handler:       _IAM_ListUsers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service_iam.proto",
}

func init() { proto.RegisterFile("service_iam.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x8d, 0xcf, 0x4c, 0xcc, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2a,
	0x28, 0xca, 0x4f, 0x4e, 0x2d, 0x2e, 0xce, 0xcc, 0xcf, 0x93, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d, 0x82,
	0x88, 0x1b, 0x9d, 0x62, 0xe4, 0x62, 0xf6, 0x74, 0xf4, 0x15, 0xb2, 0xe2, 0xe2, 0x48, 0x4f, 0x2d,
	0x89, 0x07, 0xc9, 0x08, 0x49, 0xe9, 0x21, 0x14, 0xeb, 0xb9, 0xa7, 0x96, 0x84, 0x16, 0xa7, 0x16,
	0x05, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x48, 0x09, 0x20, 0xcb, 0x81, 0x24, 0x94, 0x18, 0x84,
	0x5c, 0xb9, 0x38, 0x8a, 0xb1, 0xea, 0x0d, 0x46, 0xd5, 0x2b, 0x8d, 0x55, 0xae, 0xb8, 0x20, 0x3f,
	0xaf, 0x38, 0x55, 0x89, 0x41, 0xc8, 0x81, 0x8b, 0x2b, 0x27, 0xb3, 0x18, 0x62, 0x4e, 0xb1, 0x90,
	0x0c, 0xb2, 0x62, 0x9f, 0xcc, 0x62, 0xb0, 0xea, 0x62, 0x3c, 0xce, 0x30, 0x60, 0x4c, 0x62, 0x03,
	0xfb, 0xc9, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x74, 0xb1, 0x06, 0x00, 0x01, 0x00, 0x00,
}
