// Code generated by protoc-gen-go.
// source: session.proto
// DO NOT EDIT!

package procession

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// A session is a context for a series of requests made to the Procession
// service
type Session struct {
	// A user takes some action against the system
	User string `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *Session) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func init() {
	proto.RegisterType((*Session)(nil), "procession.Session")
}

func init() { proto.RegisterFile("session.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 75 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2e,
	0xce, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2a, 0x28, 0xca, 0x4f, 0x86,
	0x88, 0x28, 0xc9, 0x72, 0xb1, 0x07, 0x43, 0x98, 0x42, 0x42, 0x5c, 0x2c, 0xa5, 0xc5, 0xa9, 0x45,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0x76, 0x12, 0x1b, 0x58, 0x87, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0xa8, 0xdf, 0x30, 0x72, 0x42, 0x00, 0x00, 0x00,
}
