// Code generated by protoc-gen-go.
// source: user.proto
// DO NOT EDIT!

package procession

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Basic information about a user of the system
type User struct {
	Uuid        string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
	Email       string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Generation  uint32 `protobuf:"varint,100,opt,name=generation" json:"generation,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{0} }

func (m *User) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *User) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetGeneration() uint32 {
	if m != nil {
		return m.Generation
	}
	return 0
}

type GetUser struct {
	Uuid        *StringValue `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	DisplayName *StringValue `protobuf:"bytes,2,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
	Email       *StringValue `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
}

func (m *GetUser) Reset()                    { *m = GetUser{} }
func (m *GetUser) String() string            { return proto.CompactTextString(m) }
func (*GetUser) ProtoMessage()               {}
func (*GetUser) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{1} }

func (m *GetUser) GetUuid() *StringValue {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *GetUser) GetDisplayName() *StringValue {
	if m != nil {
		return m.DisplayName
	}
	return nil
}

func (m *GetUser) GetEmail() *StringValue {
	if m != nil {
		return m.Email
	}
	return nil
}

type GetUserRequest struct {
	Session *Session `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	User    *GetUser `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
}

func (m *GetUserRequest) Reset()                    { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()               {}
func (*GetUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{2} }

func (m *GetUserRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *GetUserRequest) GetUser() *GetUser {
	if m != nil {
		return m.User
	}
	return nil
}

type SetUser struct {
	Uuid        string       `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	DisplayName *StringValue `protobuf:"bytes,2,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
	Email       *StringValue `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
}

func (m *SetUser) Reset()                    { *m = SetUser{} }
func (m *SetUser) String() string            { return proto.CompactTextString(m) }
func (*SetUser) ProtoMessage()               {}
func (*SetUser) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{3} }

func (m *SetUser) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SetUser) GetDisplayName() *StringValue {
	if m != nil {
		return m.DisplayName
	}
	return nil
}

func (m *SetUser) GetEmail() *StringValue {
	if m != nil {
		return m.Email
	}
	return nil
}

type SetUserRequest struct {
	Session *Session `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	User    *SetUser `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
}

func (m *SetUserRequest) Reset()                    { *m = SetUserRequest{} }
func (m *SetUserRequest) String() string            { return proto.CompactTextString(m) }
func (*SetUserRequest) ProtoMessage()               {}
func (*SetUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{4} }

func (m *SetUserRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *SetUserRequest) GetUser() *SetUser {
	if m != nil {
		return m.User
	}
	return nil
}

type SearchUsersFilters struct {
	Uuids        []string `protobuf:"bytes,1,rep,name=uuids" json:"uuids,omitempty"`
	DisplayNames []string `protobuf:"bytes,2,rep,name=display_names,json=displayNames" json:"display_names,omitempty"`
	Emails       []string `protobuf:"bytes,3,rep,name=emails" json:"emails,omitempty"`
}

func (m *SearchUsersFilters) Reset()                    { *m = SearchUsersFilters{} }
func (m *SearchUsersFilters) String() string            { return proto.CompactTextString(m) }
func (*SearchUsersFilters) ProtoMessage()               {}
func (*SearchUsersFilters) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{5} }

func (m *SearchUsersFilters) GetUuids() []string {
	if m != nil {
		return m.Uuids
	}
	return nil
}

func (m *SearchUsersFilters) GetDisplayNames() []string {
	if m != nil {
		return m.DisplayNames
	}
	return nil
}

func (m *SearchUsersFilters) GetEmails() []string {
	if m != nil {
		return m.Emails
	}
	return nil
}

type SearchUsersRequest struct {
	Session *Session            `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Filters *SearchUsersFilters `protobuf:"bytes,2,opt,name=filters" json:"filters,omitempty"`
	Options *SearchOptions      `protobuf:"bytes,3,opt,name=options" json:"options,omitempty"`
}

func (m *SearchUsersRequest) Reset()                    { *m = SearchUsersRequest{} }
func (m *SearchUsersRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchUsersRequest) ProtoMessage()               {}
func (*SearchUsersRequest) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{6} }

func (m *SearchUsersRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *SearchUsersRequest) GetFilters() *SearchUsersFilters {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *SearchUsersRequest) GetOptions() *SearchOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "procession.User")
	proto.RegisterType((*GetUser)(nil), "procession.GetUser")
	proto.RegisterType((*GetUserRequest)(nil), "procession.GetUserRequest")
	proto.RegisterType((*SetUser)(nil), "procession.SetUser")
	proto.RegisterType((*SetUserRequest)(nil), "procession.SetUserRequest")
	proto.RegisterType((*SearchUsersFilters)(nil), "procession.SearchUsersFilters")
	proto.RegisterType((*SearchUsersRequest)(nil), "procession.SearchUsersRequest")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor8) }

var fileDescriptor8 = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x53, 0xcd, 0x4e, 0xc2, 0x40,
	0x10, 0xce, 0x02, 0xd2, 0x38, 0xfc, 0x1c, 0x56, 0xa3, 0x2b, 0x07, 0x82, 0xf5, 0x20, 0x89, 0x81,
	0x83, 0x5c, 0x8c, 0x0f, 0xa0, 0x37, 0x4d, 0xda, 0xe8, 0xd5, 0xac, 0x30, 0xc2, 0x26, 0xa5, 0xad,
	0x3b, 0x6d, 0x8c, 0x6f, 0xe0, 0x6b, 0xf8, 0x0a, 0x3e, 0xa1, 0xe9, 0xee, 0x36, 0xb6, 0x4a, 0x38,
	0x98, 0xe8, 0x09, 0x66, 0xbe, 0x6f, 0x76, 0xbe, 0x6f, 0x66, 0x0a, 0x90, 0x13, 0xea, 0x69, 0xaa,
	0x93, 0x2c, 0xe1, 0x90, 0xea, 0x64, 0x8e, 0x44, 0x2a, 0x89, 0x07, 0x5d, 0x42, 0xa9, 0xe7, 0x2b,
	0x8b, 0x0c, 0x7a, 0x64, 0xd3, 0x2e, 0xec, 0xbf, 0x68, 0x99, 0xa6, 0xa8, 0xc9, 0xc6, 0x3e, 0x41,
	0xeb, 0x8e, 0x50, 0x73, 0x0e, 0xad, 0x3c, 0x57, 0x0b, 0xc1, 0x46, 0x6c, 0xbc, 0x1b, 0x98, 0xff,
	0xfc, 0x18, 0xba, 0x0b, 0x45, 0x69, 0x24, 0x5f, 0x1f, 0x62, 0xb9, 0x46, 0xd1, 0x30, 0x58, 0xc7,
	0xe5, 0x6e, 0xe4, 0x1a, 0xf9, 0x3e, 0xec, 0xe0, 0x5a, 0xaa, 0x48, 0x34, 0x0d, 0x66, 0x03, 0x3e,
	0x04, 0x58, 0x62, 0x8c, 0x5a, 0x66, 0x2a, 0x89, 0xc5, 0x62, 0xc4, 0xc6, 0xbd, 0xa0, 0x92, 0xf1,
	0xdf, 0x19, 0x78, 0xd7, 0x98, 0x99, 0xc6, 0x67, 0x95, 0xc6, 0x9d, 0xf3, 0xc3, 0xe9, 0x97, 0x91,
	0x69, 0x98, 0x69, 0x15, 0x2f, 0xef, 0x65, 0x94, 0xa3, 0x53, 0x74, 0xb9, 0x41, 0xd1, 0x96, 0xa2,
	0x9a, 0xd4, 0x49, 0x55, 0xea, 0x96, 0x22, 0xcb, 0xf2, 0x57, 0xd0, 0x77, 0x12, 0x03, 0x7c, 0xce,
	0x91, 0x32, 0x3e, 0x01, 0xcf, 0xcd, 0xd2, 0x89, 0xdd, 0xab, 0x3d, 0x61, 0x7f, 0x83, 0x92, 0xc3,
	0x4f, 0xa1, 0x55, 0x2c, 0xc8, 0x69, 0xac, 0x71, 0xcb, 0x87, 0x0d, 0xc1, 0x7f, 0x63, 0xe0, 0x85,
	0x6e, 0x1a, 0x9b, 0xd6, 0xf0, 0xbf, 0xa6, 0xc3, 0xbf, 0x32, 0x1d, 0xd6, 0x4c, 0x2f, 0x81, 0x87,
	0xe6, 0x4c, 0x8b, 0x1c, 0x5d, 0xa9, 0x28, 0x43, 0x4d, 0xc5, 0x39, 0x15, 0x96, 0x49, 0xb0, 0x51,
	0xb3, 0x38, 0x27, 0x13, 0xf0, 0x13, 0xe8, 0x55, 0x07, 0x40, 0xa2, 0x61, 0xd0, 0x6e, 0xc5, 0x28,
	0xf1, 0x03, 0x68, 0x1b, 0x0f, 0x24, 0x9a, 0x06, 0x75, 0x91, 0xff, 0xc1, 0x6a, 0x9d, 0x7e, 0xe9,
	0xeb, 0x02, 0xbc, 0x27, 0xab, 0xd1, 0x59, 0x1b, 0xd6, 0xe9, 0xdf, 0x9d, 0x04, 0x25, 0x9d, 0xcf,
	0xc0, 0x4b, 0xd2, 0xe2, 0xea, 0xc9, 0xed, 0xe0, 0xe8, 0x67, 0xe5, 0xad, 0x25, 0x04, 0x25, 0xf3,
	0xb1, 0x6d, 0x3e, 0xce, 0xd9, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdc, 0x72, 0x78, 0x3d, 0xe3,
	0x03, 0x00, 0x00,
}
