// Code generated by protoc-gen-go.
// source: user.proto
// DO NOT EDIT!

package procession

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Basic information about a user of the system
type User struct {
	Uuid        string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Email       string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
	Slug        string `protobuf:"bytes,4,opt,name=slug" json:"slug,omitempty"`
	Generation  uint32 `protobuf:"varint,100,opt,name=generation" json:"generation,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *User) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *User) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *User) GetGeneration() uint32 {
	if m != nil {
		return m.Generation
	}
	return 0
}

type UserGetRequest struct {
	Session *Session `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Search  string   `protobuf:"bytes,2,opt,name=search" json:"search,omitempty"`
}

func (m *UserGetRequest) Reset()                    { *m = UserGetRequest{} }
func (m *UserGetRequest) String() string            { return proto.CompactTextString(m) }
func (*UserGetRequest) ProtoMessage()               {}
func (*UserGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *UserGetRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *UserGetRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type SetUserFields struct {
	Email       *StringValue `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	DisplayName *StringValue `protobuf:"bytes,3,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
}

func (m *SetUserFields) Reset()                    { *m = SetUserFields{} }
func (m *SetUserFields) String() string            { return proto.CompactTextString(m) }
func (*SetUserFields) ProtoMessage()               {}
func (*SetUserFields) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *SetUserFields) GetEmail() *StringValue {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *SetUserFields) GetDisplayName() *StringValue {
	if m != nil {
		return m.DisplayName
	}
	return nil
}

type SetUserRequest struct {
	Session    *Session       `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Search     *StringValue   `protobuf:"bytes,2,opt,name=search" json:"search,omitempty"`
	UserFields *SetUserFields `protobuf:"bytes,3,opt,name=user_fields,json=userFields" json:"user_fields,omitempty"`
}

func (m *SetUserRequest) Reset()                    { *m = SetUserRequest{} }
func (m *SetUserRequest) String() string            { return proto.CompactTextString(m) }
func (*SetUserRequest) ProtoMessage()               {}
func (*SetUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

func (m *SetUserRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *SetUserRequest) GetSearch() *StringValue {
	if m != nil {
		return m.Search
	}
	return nil
}

func (m *SetUserRequest) GetUserFields() *SetUserFields {
	if m != nil {
		return m.UserFields
	}
	return nil
}

type SetUserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *SetUserResponse) Reset()                    { *m = SetUserResponse{} }
func (m *SetUserResponse) String() string            { return proto.CompactTextString(m) }
func (*SetUserResponse) ProtoMessage()               {}
func (*SetUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{4} }

func (m *SetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UserListFilters struct {
	Uuids        []string `protobuf:"bytes,1,rep,name=uuids" json:"uuids,omitempty"`
	DisplayNames []string `protobuf:"bytes,2,rep,name=display_names,json=displayNames" json:"display_names,omitempty"`
	Emails       []string `protobuf:"bytes,3,rep,name=emails" json:"emails,omitempty"`
	Slugs        []string `protobuf:"bytes,4,rep,name=slugs" json:"slugs,omitempty"`
}

func (m *UserListFilters) Reset()                    { *m = UserListFilters{} }
func (m *UserListFilters) String() string            { return proto.CompactTextString(m) }
func (*UserListFilters) ProtoMessage()               {}
func (*UserListFilters) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{5} }

func (m *UserListFilters) GetUuids() []string {
	if m != nil {
		return m.Uuids
	}
	return nil
}

func (m *UserListFilters) GetDisplayNames() []string {
	if m != nil {
		return m.DisplayNames
	}
	return nil
}

func (m *UserListFilters) GetEmails() []string {
	if m != nil {
		return m.Emails
	}
	return nil
}

func (m *UserListFilters) GetSlugs() []string {
	if m != nil {
		return m.Slugs
	}
	return nil
}

type UserListRequest struct {
	Session *Session         `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Filters *UserListFilters `protobuf:"bytes,2,opt,name=filters" json:"filters,omitempty"`
	Options *SearchOptions   `protobuf:"bytes,3,opt,name=options" json:"options,omitempty"`
}

func (m *UserListRequest) Reset()                    { *m = UserListRequest{} }
func (m *UserListRequest) String() string            { return proto.CompactTextString(m) }
func (*UserListRequest) ProtoMessage()               {}
func (*UserListRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{6} }

func (m *UserListRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *UserListRequest) GetFilters() *UserListFilters {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *UserListRequest) GetOptions() *SearchOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "procession.User")
	proto.RegisterType((*UserGetRequest)(nil), "procession.UserGetRequest")
	proto.RegisterType((*SetUserFields)(nil), "procession.SetUserFields")
	proto.RegisterType((*SetUserRequest)(nil), "procession.SetUserRequest")
	proto.RegisterType((*SetUserResponse)(nil), "procession.SetUserResponse")
	proto.RegisterType((*UserListFilters)(nil), "procession.UserListFilters")
	proto.RegisterType((*UserListRequest)(nil), "procession.UserListRequest")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0x5b, 0xd3, 0x88, 0x71, 0x9c, 0xa2, 0x05, 0xc1, 0x52, 0x24, 0x14, 0x0c, 0x87, 0x5e,
	0x1a, 0xa4, 0x56, 0x08, 0xa9, 0x1f, 0x50, 0x2e, 0x08, 0x24, 0x57, 0xc0, 0x31, 0x5a, 0xe2, 0x49,
	0x58, 0xc9, 0xb1, 0xcd, 0xce, 0x5a, 0x88, 0xfc, 0x00, 0x3f, 0xc3, 0x47, 0xa2, 0xd9, 0x5d, 0x87,
	0x0d, 0xa2, 0x39, 0xe4, 0x94, 0x7d, 0x3b, 0x93, 0x99, 0xf7, 0xde, 0x3e, 0x03, 0xf4, 0x84, 0x66,
	0xd6, 0x99, 0xd6, 0xb6, 0x02, 0x3a, 0xd3, 0x2e, 0x90, 0x48, 0xb7, 0xcd, 0xd9, 0x98, 0x50, 0x99,
	0xc5, 0x37, 0x5f, 0x39, 0xcb, 0xc9, 0x5f, 0x07, 0x38, 0xf9, 0x61, 0x54, 0xd7, 0xa1, 0x21, 0x8f,
	0x8b, 0x5f, 0x09, 0xa4, 0x9f, 0x08, 0x8d, 0x10, 0x90, 0xf6, 0xbd, 0xae, 0x64, 0x32, 0x4d, 0xce,
	0xef, 0x97, 0xee, 0x2c, 0x1e, 0xc1, 0x3d, 0x5c, 0x2b, 0x5d, 0xcb, 0x23, 0x77, 0xe9, 0x81, 0x78,
	0x01, 0xe3, 0x4a, 0x53, 0x57, 0xab, 0x9f, 0xf3, 0x46, 0xad, 0x51, 0x1e, 0xbb, 0x62, 0x16, 0xee,
	0x3e, 0xa8, 0x35, 0xf2, 0x30, 0xaa, 0xfb, 0x95, 0x4c, 0xfd, 0x30, 0x3e, 0x8b, 0xe7, 0x00, 0x2b,
	0x6c, 0xd0, 0x28, 0xab, 0xdb, 0x46, 0x56, 0xd3, 0xe4, 0x3c, 0x2f, 0xa3, 0x9b, 0xe2, 0x0b, 0x4c,
	0x98, 0xc8, 0x3b, 0xb4, 0x25, 0x7e, 0xef, 0x91, 0xac, 0xb8, 0x80, 0x51, 0x20, 0xef, 0x58, 0x65,
	0x97, 0x0f, 0x67, 0x7f, 0x65, 0xce, 0x6e, 0xfd, 0x6f, 0x39, 0xf4, 0x88, 0xc7, 0x70, 0xe2, 0x95,
	0x07, 0xba, 0x01, 0x15, 0x1b, 0xc8, 0x6f, 0xd1, 0xf2, 0xec, 0x1b, 0x8d, 0x75, 0x45, 0xe2, 0x22,
	0x96, 0x95, 0x5d, 0x3e, 0xd9, 0x99, 0x6a, 0x8d, 0x6e, 0x56, 0x9f, 0x55, 0xdd, 0xe3, 0xa0, 0xf7,
	0xfa, 0x3f, 0x7a, 0xf7, 0xfc, 0x2b, 0x36, 0xa2, 0xf8, 0x9d, 0xc0, 0x24, 0x2c, 0x3f, 0x50, 0xd5,
	0xeb, 0x1d, 0x55, 0x7b, 0xf6, 0x86, 0x36, 0x71, 0x0d, 0x19, 0x07, 0x63, 0xbe, 0x74, 0x62, 0x03,
	0xdb, 0xa7, 0xbb, 0x3b, 0x22, 0x37, 0x4a, 0x17, 0x23, 0x7f, 0x2e, 0xde, 0xc2, 0xe9, 0x96, 0x2d,
	0x75, 0x6d, 0x43, 0x28, 0x5e, 0x41, 0xca, 0x0d, 0x81, 0xeb, 0x83, 0x78, 0x8e, 0xeb, 0x73, 0xd5,
	0x62, 0x03, 0xa7, 0x8c, 0xde, 0x6b, 0xb2, 0x37, 0xba, 0xb6, 0x68, 0x88, 0xc3, 0xc3, 0x21, 0x22,
	0x99, 0x4c, 0x8f, 0x39, 0x3c, 0x0e, 0x88, 0x97, 0x90, 0xc7, 0x66, 0x92, 0x3c, 0x72, 0xd5, 0x71,
	0x64, 0x1a, 0xf1, 0x4b, 0x3a, 0xeb, 0x99, 0x3d, 0x57, 0x03, 0xe2, 0x91, 0x1c, 0x25, 0x92, 0xa9,
	0x1f, 0xe9, 0x00, 0x7b, 0xbc, 0x5d, 0x7e, 0xa0, 0xc9, 0x6f, 0x60, 0xb4, 0xf4, 0xb4, 0x83, 0xcb,
	0xcf, 0xfe, 0xd5, 0x19, 0x29, 0x2b, 0x87, 0x5e, 0x71, 0x05, 0xa3, 0xb6, 0xe3, 0xf0, 0xde, 0x61,
	0x33, 0xbf, 0xc7, 0x47, 0xdf, 0x50, 0x0e, 0x9d, 0x5f, 0x4f, 0xdc, 0x87, 0x77, 0xf5, 0x27, 0x00,
	0x00, 0xff, 0xff, 0x05, 0x8a, 0x5a, 0x90, 0xbf, 0x03, 0x00, 0x00,
}
