// Code generated by protoc-gen-go.
// source: user.proto
// DO NOT EDIT!

package procession

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Basic information about a user of the system
type User struct {
	Uuid        string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Email       string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
	Slug        string `protobuf:"bytes,4,opt,name=slug" json:"slug,omitempty"`
	Generation  uint32 `protobuf:"varint,100,opt,name=generation" json:"generation,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *User) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *User) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *User) GetGeneration() uint32 {
	if m != nil {
		return m.Generation
	}
	return 0
}

type GetUserFields struct {
	Uuid        *StringValue `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Email       *StringValue `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	DisplayName *StringValue `protobuf:"bytes,3,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
	Slug        *StringValue `protobuf:"bytes,4,opt,name=slug" json:"slug,omitempty"`
}

func (m *GetUserFields) Reset()                    { *m = GetUserFields{} }
func (m *GetUserFields) String() string            { return proto.CompactTextString(m) }
func (*GetUserFields) ProtoMessage()               {}
func (*GetUserFields) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *GetUserFields) GetUuid() *StringValue {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *GetUserFields) GetEmail() *StringValue {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *GetUserFields) GetDisplayName() *StringValue {
	if m != nil {
		return m.DisplayName
	}
	return nil
}

func (m *GetUserFields) GetSlug() *StringValue {
	if m != nil {
		return m.Slug
	}
	return nil
}

type GetUserRequest struct {
	Session      *Session       `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	SearchFields *GetUserFields `protobuf:"bytes,2,opt,name=search_fields,json=searchFields" json:"search_fields,omitempty"`
}

func (m *GetUserRequest) Reset()                    { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()               {}
func (*GetUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func (m *GetUserRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *GetUserRequest) GetSearchFields() *GetUserFields {
	if m != nil {
		return m.SearchFields
	}
	return nil
}

type SetUserFields struct {
	Email       *StringValue `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	DisplayName *StringValue `protobuf:"bytes,3,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
}

func (m *SetUserFields) Reset()                    { *m = SetUserFields{} }
func (m *SetUserFields) String() string            { return proto.CompactTextString(m) }
func (*SetUserFields) ProtoMessage()               {}
func (*SetUserFields) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{3} }

func (m *SetUserFields) GetEmail() *StringValue {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *SetUserFields) GetDisplayName() *StringValue {
	if m != nil {
		return m.DisplayName
	}
	return nil
}

type SetUserRequest struct {
	Session      *Session       `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	SearchFields *GetUserFields `protobuf:"bytes,2,opt,name=search_fields,json=searchFields" json:"search_fields,omitempty"`
	UserFields   *SetUserFields `protobuf:"bytes,3,opt,name=user_fields,json=userFields" json:"user_fields,omitempty"`
}

func (m *SetUserRequest) Reset()                    { *m = SetUserRequest{} }
func (m *SetUserRequest) String() string            { return proto.CompactTextString(m) }
func (*SetUserRequest) ProtoMessage()               {}
func (*SetUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{4} }

func (m *SetUserRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *SetUserRequest) GetSearchFields() *GetUserFields {
	if m != nil {
		return m.SearchFields
	}
	return nil
}

func (m *SetUserRequest) GetUserFields() *SetUserFields {
	if m != nil {
		return m.UserFields
	}
	return nil
}

type SetUserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *SetUserResponse) Reset()                    { *m = SetUserResponse{} }
func (m *SetUserResponse) String() string            { return proto.CompactTextString(m) }
func (*SetUserResponse) ProtoMessage()               {}
func (*SetUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{5} }

func (m *SetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type ListUsersFilters struct {
	Uuids        []string `protobuf:"bytes,1,rep,name=uuids" json:"uuids,omitempty"`
	DisplayNames []string `protobuf:"bytes,2,rep,name=display_names,json=displayNames" json:"display_names,omitempty"`
	Emails       []string `protobuf:"bytes,3,rep,name=emails" json:"emails,omitempty"`
}

func (m *ListUsersFilters) Reset()                    { *m = ListUsersFilters{} }
func (m *ListUsersFilters) String() string            { return proto.CompactTextString(m) }
func (*ListUsersFilters) ProtoMessage()               {}
func (*ListUsersFilters) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{6} }

func (m *ListUsersFilters) GetUuids() []string {
	if m != nil {
		return m.Uuids
	}
	return nil
}

func (m *ListUsersFilters) GetDisplayNames() []string {
	if m != nil {
		return m.DisplayNames
	}
	return nil
}

func (m *ListUsersFilters) GetEmails() []string {
	if m != nil {
		return m.Emails
	}
	return nil
}

type ListUsersRequest struct {
	Session *Session          `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Filters *ListUsersFilters `protobuf:"bytes,2,opt,name=filters" json:"filters,omitempty"`
	Options *SearchOptions    `protobuf:"bytes,3,opt,name=options" json:"options,omitempty"`
}

func (m *ListUsersRequest) Reset()                    { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string            { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()               {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{7} }

func (m *ListUsersRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *ListUsersRequest) GetFilters() *ListUsersFilters {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *ListUsersRequest) GetOptions() *SearchOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "procession.User")
	proto.RegisterType((*GetUserFields)(nil), "procession.GetUserFields")
	proto.RegisterType((*GetUserRequest)(nil), "procession.GetUserRequest")
	proto.RegisterType((*SetUserFields)(nil), "procession.SetUserFields")
	proto.RegisterType((*SetUserRequest)(nil), "procession.SetUserRequest")
	proto.RegisterType((*SetUserResponse)(nil), "procession.SetUserResponse")
	proto.RegisterType((*ListUsersFilters)(nil), "procession.ListUsersFilters")
	proto.RegisterType((*ListUsersRequest)(nil), "procession.ListUsersRequest")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0xcf, 0xee, 0xd2, 0x40,
	0x10, 0xce, 0x4a, 0xfd, 0x11, 0x07, 0x8a, 0x64, 0x35, 0x5a, 0x89, 0x31, 0x58, 0x3d, 0x90, 0x10,
	0x38, 0x48, 0xa2, 0x09, 0x07, 0x8f, 0x78, 0x31, 0x9a, 0x2c, 0xd1, 0x2b, 0x59, 0xe9, 0x80, 0x9b,
	0x94, 0xb6, 0xee, 0xb4, 0x31, 0x7a, 0xf1, 0xe8, 0xdb, 0xf8, 0x02, 0xbe, 0x86, 0x0f, 0x64, 0xf6,
	0x4f, 0x75, 0xeb, 0x1f, 0x0e, 0x1e, 0xfc, 0x9d, 0xe8, 0xcc, 0x7c, 0x33, 0x7c, 0xdf, 0x37, 0x9d,
	0x02, 0x34, 0x84, 0x7a, 0x59, 0xe9, 0xb2, 0x2e, 0x39, 0x54, 0xba, 0xdc, 0x23, 0x91, 0x2a, 0x8b,
	0xc9, 0x90, 0x50, 0xea, 0xfd, 0x5b, 0x57, 0x99, 0xc4, 0xe4, 0xd2, 0x3e, 0x1c, 0xbd, 0xd7, 0xb2,
	0xaa, 0x50, 0x93, 0x8b, 0xd3, 0xcf, 0x0c, 0xa2, 0x57, 0x84, 0x9a, 0x73, 0x88, 0x9a, 0x46, 0x65,
	0x09, 0x9b, 0xb2, 0xd9, 0x35, 0x61, 0x9f, 0xf9, 0x4d, 0xb8, 0x8a, 0x27, 0xa9, 0xf2, 0xe4, 0x8a,
	0x4d, 0xba, 0x80, 0xdf, 0x87, 0x61, 0xa6, 0xa8, 0xca, 0xe5, 0x87, 0x5d, 0x21, 0x4f, 0x98, 0xf4,
	0x6c, 0x71, 0xe0, 0x73, 0x2f, 0xe4, 0x09, 0xcd, 0x30, 0xca, 0x9b, 0x63, 0x12, 0xb9, 0x61, 0xe6,
	0x99, 0xdf, 0x03, 0x38, 0x62, 0x81, 0x5a, 0xd6, 0xaa, 0x2c, 0x92, 0x6c, 0xca, 0x66, 0xb1, 0x08,
	0x32, 0xe9, 0x37, 0x06, 0xf1, 0x33, 0xac, 0x0d, 0x99, 0x8d, 0xc2, 0x3c, 0x23, 0x3e, 0x0f, 0x28,
	0x0d, 0x1e, 0xdd, 0x5e, 0xfe, 0xd4, 0xb8, 0xdc, 0xd6, 0x5a, 0x15, 0xc7, 0xd7, 0x32, 0x6f, 0xd0,
	0x73, 0x5d, 0x84, 0x5c, 0xcf, 0xa0, 0xbd, 0x88, 0xf5, 0x1f, 0x44, 0x9c, 0xe9, 0xea, 0xa8, 0x9b,
	0x07, 0xea, 0xce, 0xf1, 0x32, 0xa0, 0xf4, 0x13, 0x8c, 0xbc, 0x2a, 0x81, 0xef, 0x1a, 0xa4, 0x9a,
	0x2f, 0xa0, 0xef, 0x77, 0xe2, 0x95, 0xdd, 0xe8, 0x4c, 0x70, 0xbf, 0xa2, 0xc5, 0xf0, 0xa7, 0x10,
	0xbb, 0x85, 0xee, 0x0e, 0xd6, 0x16, 0x2f, 0xf0, 0x4e, 0xd8, 0xd4, 0xf1, 0x4d, 0xf8, 0x17, 0xc0,
	0x45, 0xe9, 0x47, 0x88, 0xb7, 0x1d, 0x5b, 0xff, 0x9f, 0x53, 0xe9, 0x57, 0x06, 0xa3, 0xed, 0x65,
	0xaa, 0xe7, 0x6b, 0x18, 0x98, 0x33, 0x69, 0xbb, 0x7b, 0xbf, 0x77, 0x77, 0xcc, 0x11, 0xf6, 0xa8,
	0xbc, 0x73, 0x4f, 0xe0, 0xfa, 0x0f, 0xf2, 0x54, 0x95, 0x05, 0x21, 0x7f, 0x08, 0x91, 0x01, 0x78,
	0xea, 0xe3, 0x70, 0x8e, 0xc5, 0xd9, 0x6a, 0x8a, 0x30, 0x7e, 0xae, 0xc8, 0x76, 0xd2, 0x46, 0xe5,
	0x35, 0x6a, 0x32, 0xb7, 0x64, 0xde, 0x53, 0x4a, 0xd8, 0xb4, 0x67, 0x6e, 0xc9, 0x06, 0xfc, 0x01,
	0xc4, 0xa1, 0xb9, 0x46, 0x9e, 0xa9, 0x0e, 0x03, 0x13, 0x89, 0xdf, 0x82, 0x0b, 0xbb, 0x0a, 0x43,
	0xdf, 0x54, 0x7d, 0x94, 0x7e, 0x61, 0xc1, 0xff, 0xfc, 0xa3, 0xbf, 0x8f, 0xa1, 0x7f, 0x70, 0x0c,
	0xbd, 0xb3, 0x77, 0x43, 0xf8, 0xaf, 0x2a, 0x44, 0x0b, 0xe6, 0x2b, 0xe8, 0x97, 0x95, 0xb9, 0xdb,
	0xbf, 0x78, 0x6a, 0x56, 0xf0, 0xd2, 0x01, 0x44, 0x8b, 0x7c, 0x73, 0x61, 0xbf, 0x39, 0xab, 0xef,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x3a, 0x8c, 0x84, 0x7e, 0xba, 0x04, 0x00, 0x00,
}
